name: publish-standalone

inputs:
  project:
    description: path to csproj to publish
  runtime:
    description: dotnet runtime to publish against
    required: true
  version:
    description: version name to include in the zip filename (x.y.z)
    required: true

runs:
  using: "composite"

  steps:
    - name: dotnet publish
      shell: pwsh
      run: dotnet publish ${{inputs.project}} -c Release -r ${{inputs.runtime}} --self-contained /p:PublishAot=true /p:DebugSymbols=False /p:DebugType=None -o drop/publish/${{inputs.runtime}}

    - name: zip
      shell: pwsh
      run: |
        mkdir -p drop/bin/${{inputs.runtime}}
        Compress-Archive -Path drop/publish/${{inputs.runtime}}/* -DestinationPath drop/bin/${{inputs.runtime}}/csv-merge-${{inputs.runtime}}-${{inputs.version}}.zip

    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.runtime}}
        path: drop/bin/${{inputs.runtime}}
        if-no-files-found: error
