name: publish-standalone

inputs:
  runtime:
    description: dotnet runtime to publish against
  version:
    description: version name to include in the zip filename

runs:
  using: "composite"

  steps:
    - name: dotnet publish
      shell: bash
      run: dotnet publish ./CsvMerge/CsvMerge.csproj -c Release -r ${{inputs.runtime}} --self-contained /p:PublishAot=true /p:DebugSymbols=False /p:DebugType=None -o drop/publish/${{inputs.runtime}}

    - name: zip
      shell: bash
      run: |
        mkdir -p ../../bin
        zip -r ../../bin/csv-merge-${{inputs.runtime}}-v${{inputs.version}}.zip .
      working-directory: drop/publish/${{inputs.runtime}}

    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.runtime}}
        path: drop/bin/${{inputs.runtime}}
        if-no-files-found: error
