name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: dotnet tool restore
        run: dotnet tool restore

      - name: dotnet tool csharpier check
        run: dotnet csharpier --check .

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --no-restore

      - name: dotnet test
        run: dotnet test --no-build --verbosity normal

      - name: tag version
        run: |
          tagversion=$(dotnet nbgv tag | grep ": git push" | cut -f2- -dv)
          git push origin v$tagversion
